### ISSUE TITLE
The version is npm is outdated (0.0.1 --> 0.0.2)

### ISSUE THREAD

**Issue by juhamust** [toddmotto/angular-component#10]
Please update the release also in npm: https://www.npmjs.com/package/angular-component

Related to #1

**Comment by CNBorn** [comment]
@benoror since he is the maintainer.

**Comment by benoror** [comment]
done! maybe it would be a good idea to add `npm publish && ...` to an npm script, something like [semantic-release](https://www.npmjs.com/package/semantic-release) / [publish-latest](https://www.npmjs.com/package/publish-latest)

**Comment by toddmotto** [comment]
Version `0.0.3` is latest and pushed to npm.
