### ISSUE TITLE
Unknown provider: componentFactoryNamingConventions

### ISSUE THREAD

**Issue by krasevych** [toddmotto/angular-component#12]
Hello,
I use v0.1.0; and angular 1.5;
I have problems. When I try to run my app I got this error: 
Error: [$injector:unpr] Unknown provider: componentFactoryNamingConventions
for v0.0.1 everything is ok.

**Comment by toddmotto** [comment]
Any chance of a quick jsfiddle to isolate the issue? Can use this setup as a base: https://jsfiddle.net/toddmotto/3yuax91m/

**Comment by krasevych** [comment]
I found the cause.
I use Bower and I write "angular-component": "*";
but there is the same name of the module:
https://github.com/kennethlynne/angular-component
