### ISSUE TITLE
one way binding syntax doesn't work

### ISSUE THREAD

**Issue by vanceingalls** [toddmotto/angular-component#14]
when using the following syntax for one way data binding

```
binding: {
  property: "<"
}
```

the following error is thrown

```
Error: [$compile:iscp] Invalid isolate scope definition for directive 'componentName'. Definition: {... property: '<' ...}
```

**Comment by toddmotto** [comment]
What angular version are you using?

@toddmotto

**Comment by vanceingalls** [comment]
1.3.20

**Comment by toddmotto** [comment]
One-way binding only works in 1.5+ as it's new - it needed to be polyfilled (which I've just done here: https://github.com/toddmotto/angular-component/commit/b737e2782c75ff8852fea8943f180080896efa9e) if you wouldn't mind testing.

**Comment by winnemucca** [comment]
I actually got this on 1.5.
