### ISSUE TITLE
Add support for `require` object and $onInit controller method

### ISSUE THREAD

**Issue by bisubus** [toddmotto/angular-component#17]
Technically they are the features of directives and not components, but it would require too much fragile patching in versions prior to 1.5.

Directives can live fine without them, but they are essential for [intercomponent communication](https://docs.angularjs.org/guide/component#intercomponent-communication), components have no alternatives to `link` and thus are barely usable without them.

Can we add them, please?

**Comment by toddmotto** [comment]
Do you think polyfilling this would be achievable? Unsure if there are things here that rely on Angular internals.

**Comment by bisubus** [comment]
@toddmotto Absolutely. I believe it has to be something like [this](https://github.com/bisubus/angular-component/commit/8ebd7364e15cc422165bca22a411a12d67f64f3f). It seems to be quite close to what $compile does in 1.5.

**Comment by toddmotto** [comment]
Awesome. Do you think hi-jacking the Controller would be better and then running this.oninit first?

**Comment by bisubus** [comment]
Yes, I'm quite sure about that, that's what is done under the hood. All required controllers are available [as instance properties](https://github.com/angular/angular.js/blob/v1.5.0/src/ng/compile.js#L2427) when [$onInit runs](https://github.com/angular/angular.js/blob/v1.5.0/src/ng/compile.js#L2434) on instance, that's its purpose.

I fixed it, it should be preLink to maintain the proper order of $onInit execution.

**Comment by toddmotto** [comment]
Sounds good to me, let's get this added!

**Comment by bisubus** [comment]
Ok. It looks like there's nothing to break down here.

**Comment by pablolazaro** [comment]
Hi there,

On my project we are really interested on using this polyfill mainly for the $onInit method.

Do you have scheduled the merge of that pull request?

Thank you very much.

**Comment by toddmotto** [comment]
Hey. Super busy at moment, will try land it this week, you can pull in the
code from the PR for now though if you'd like as a temporary solution!

On 14 March 2016 at 11:40, Pablo Lázaro notifications@github.com wrote:

> Hi there,
> 
> On my project we are really interested on using this polyfill mainly for
> the $onInit method.
> 
> Do you have scheduled the merge of that pull request?
> 
> Thank you very much.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/toddmotto/angular-component/issues/17#issuecomment-196274079
> .

## 

@toddmotto
