### ISSUE TITLE
[QUESTION] - Angular2 Components Features

### ISSUE THREAD

**Issue by matheuspoleza** [toddmotto/angular-component#21]
### Question

Make sense we work to upgrade some ng2 features to this project ? 
### Features:
- [ ] Component Style (css)
- [ ] Component Router  

![selection_394](https://cloud.githubusercontent.com/assets/8049914/14640138/7cddf812-0616-11e6-8a2b-2ce490166b01.png)
![selection_393](https://cloud.githubusercontent.com/assets/8049914/14640137/7cdd2bda-0616-11e6-95dd-541692e13359.png)
### Why?

Actually, some people cannot update to ng2 yet (Legacy code, product roadmap and stuff). I think this isn't so complicated.

**Comment by toddmotto** [comment]
Any changes polyfilled here will have to exist in the main core beforehand, open an issue up if further things drop into Angular 1.5.x :)
