### ISSUE TITLE
Multiple One Way Bindings

### ISSUE THREAD

**Issue by tschant** [toddmotto/angular-component#31]
I am having some issues with multiple one way bindings and the `$onChange`.
It appears that the last one way bind variable is the only one that detects changes.

Here is a JS Fiddle https://jsfiddle.net/9jkr44mx/
(I forked it from the one way binding fiddle you had here https://jsfiddle.net/toddmotto/umudwa9u/.)

All changes to `count` and `other` are being treated as `other` on the component and not individually.
After the timeout, count should be updated to 100 and other should still be 0, but `other` gets updated to 100 and `count` is not present on the controller/component scope.

**Comment by toddmotto** [comment]
Hey @tschant ! So, I'm currently working on a fix for this - it's due to the way $onChanges works and it's a little complex to polyfill this alongside `'<'` syntax. I'm not going to be able to fix it at the moment, if you have any time to help out to fix it then I'd be all appreciated!

**Comment by TehShrike** [comment]
I'd be happy to add some tests once #28 wraps up.

**Comment by toddmotto** [comment]
@TehShrike We're taking the tests from the Angular 1.5.x branch, so as long as those tests pass with using the 1.3.0 version of Angular then we're all good, there is just a couple of tests that need code to make them pass right now :)

**Comment by anthwinter** [comment]
@toddmotto - I have a fix for this issue, I could raise a PR for it if you like?

If so, should I just commit my src files, or should I include the dist files too.

**Comment by toddmotto** [comment]
@anthwinter Sure! Did you wanna add me on Skype so we can discuss the ES6 branch?
