### ISSUE TITLE
Component without the "bindings" does not get an isolate scope

### ISSUE THREAD

**Issue by LulzAugusto** [toddmotto/angular-component#6]
Hi @toddmotto. I'm using your patch and I noticed that when I omit the `bindings` property of the component below, it doesn't get an isolate scope, while using angular.js-1.5.0-rc.0 it does. See:

![1](https://cloud.githubusercontent.com/assets/254107/12209519/45ea5834-b632-11e5-8330-2cac14f77dd8.png)
![2](https://cloud.githubusercontent.com/assets/254107/12209521/47939e52-b632-11e5-9959-05b19458c659.png)

ps: should've cropped the images srry

**Comment by toddmotto** [comment]
Fixed in https://github.com/toddmotto/angular-component/commit/33113bf8162b8aa291a190b51499cce35605f663
