### ISSUE TITLE
ui-router resolve

### ISSUE THREAD

**Issue by menems** [toddmotto/angular-component#8]
Hi

I saw that you remove bindings options 2 days ago.

So now how we can pass ui-router resolve injection on the component?

I use ui-router and component combined like that:

```
.state('test, {
    url: '/',
    template: '<my-component/>',
    resolve: {
        testData: function(service) {
              return service.promise();
        }
    }
}
```

before i used:

```
.state('test, {
    url: '/',
    template: '<my-component data="test.data"/>',
   controllerAs: 'test',
   controller: function(testData) {
      this.data = testData;
   }
    resolve: {
        testData: function(service) {
              return service.promise();
        }
    }
}
```

What is the best practice now to have the same behaviour, that is the controller is instanciate after the promise is resolved?

**Comment by toddmotto** [comment]
Does this issue need to remain open now that the bindings were added back in?

**Comment by menems** [comment]
yes, thanks

**Comment by asadsahi** [comment]
@toddmotto I am having this problem trying to use resolved objects from ui-router inside component, but these object are undefined when trying to access from components.

In angular 1.5 with ui router, we can place resolved data like this:
 
`<my-component data="$resolve.MyData".....
`
and resolve object looks something like this:
```
 resolve: {
                        MyData: ['myservice', function (myservice) {
                            return myservice.getDataAsync()
                        }],       
```                   
We have been working with angular 1.5, but now have to roll back to 1.3 for some issues and for components we are using your polyfill. Good job :+1: 

After adding polyfill, I have tried both approaches:

1) bindings 
```
 bindings: {
                data: '<MyData' // Doesn't work
                 //data: '<' // This doesn't work either
            }
```
2) Injecting into controller of component:

 MyController.$inject = ['data'];
 function  MyController(data) {

But **data** object received from route resolve is always undefined. 

It will be really helpful if an example with router can be created. Thanks

**Comment by asadsahi** [comment]
@menems did this work? I can't seem to get it working.

**Comment by asadsahi** [comment]
Ignore that, got it working, thanks @menems @toddmotto . Great work. 👍
