### ISSUE TITLE
Can't set any isolate scope properties

### ISSUE THREAD

**Issue by azevedo** [toddmotto/angular-component#9]
The latest [commit](https://github.com/toddmotto/angular-component/commit/fc618863557249f74de00b18224719c73448275e#diff-18c2213bbc16afbc7669912ba0382d88R47) makes it impossible to set any isolate scope properties, as it is not extendable anymore.

**Comment by menems** [comment]
#8 related

You replace the name as controllerAs by '$ctrl', why ?
so now we have to explicitly add controllerAs ...

**Comment by benoror** [comment]
https://github.com/angular/angular.js/pull/13710 cc @azevedo-252 @menems

**Comment by azevedo** [comment]
@menems  I understand that, and the issue is not about that feature in particular.
What I mean is that we can no longer set isolate scope properties with the `bindings` property, like so

```
angular
.module('app', [])
.component('counter', {
  bindings: {
    count: '='
  },
  ...
});
```

because it no longer maps it to the real `scope` property of the DDO. What you get in the end is something like:

```
angular
.module('app', [])
.directive('counter', {
  scope: {}, // notice `count` is missing
  ...
});
```

This is the [change](https://github.com/toddmotto/angular-component/commit/fc618863557249f74de00b18224719c73448275e#diff-18c2213bbc16afbc7669912ba0382d88R47) that causes this. It doesn't assign `options.bindings` anywhere.

**Comment by toddmotto** [comment]
@azevedo-252 You okay to test last commit on `master`? :)

**Comment by toddmotto** [comment]
Latest changes should mirror the new 1.5 syntax:

``` js
scope: options.bindings || {},
bindToController: !!options.bindings,
```

Set `scope: { foo: '=' }` or `scope: {}` and `bindToController: [Boolean]`. That way it works on 1.3 still.

**Comment by toddmotto** [comment]
@benoror If the last commit fixes, then `0.0.3` is good to go on npm

**Comment by azevedo** [comment]
@toddmotto it's working
:+1:

**Comment by toddmotto** [comment]
@azevedo-252 Awesome, thanks! :)

**Comment by benoror** [comment]
`npm publish`'ed :+1:
